# Copyright 2025, Battelle Energy Alliance, LLC, ALL RIGHTS RESERVED

apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-db
  labels:
    app: portal-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portal-db
  template:
    metadata:
      labels:
        app: portal-db
    spec:
      securityContext:
        fsGroup: 10001
      containers:
        - image: 869935092417.dkr.ecr.us-west-1.amazonaws.com/inl-image-registry/portalsql:latest
          imagePullPolicy: Always
          name: portal-db
          ports:
            - containerPort: 1433
          env:
            - name: MSSQL_SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-creds
                  key: password
            - name: ACCEPT_EULA
              value: "Y"
            - name: MSSQL_PID
              value: "Express"
          volumeMounts:
            - name: portal-db-storage
              mountPath: /var/opt/mssql
      volumes:
        - name: portal-db-storage
          persistentVolumeClaim:
            claimName: portal-db-pvc
      imagePullSecrets:
        - name: inl-registry-creds

---
apiVersion: v1
kind: Service
metadata:
  name: portal-db
spec:
  selector:
    app: portal-db
  ports:
    - protocol: TCP
      port: 1433
      targetPort: 1433

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: portal-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: longhorn
