# Copyright 2025, Battelle Energy Alliance, LLC, ALL RIGHTS RESERVED

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    description: "Data Ingestion"
    owner: "INL"
    version: "1.0.0"
  labels:
    app: "data-ingestion"
    environment: "prod"
  name: data-ingestion
  namespace: argocd
spec:
  destination:
    name: ""
    namespace: data-ingestion
    server: "https://kubernetes.default.svc"
  source:
    path: k8s/manifests/data-ingestion
    repoURL: "git@github.inl.gov:COREII/COREII-Data-Lake.git"
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
